# Generated by Django 4.2.2 on 2023-07-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toppings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topping",
            name="description",
            field=models.TextField(default="Tasty pizza treat"),
            preserve_default=False,
        ),
    ]
